### ISSUE TITLE
endless condition + unnecessary return

### ISSUE THREAD

**Issue by xandrck** [alex-rns/med_helper#136]
https://github.com/alex-rns/med_helper/blob/58c076f69090b6c0c017d8fe2c1f46f0088f0cf6/app/helpers/events_helper.rb#L63

После выполнения условия мы больше ничего не возвращаем, по-этому return не нужны.

Нужно чуток подумать над подходом чтобы сделать его более гибким, а если бы было в условии 100 разных значений?
У вас день недели совпадает с елементом массива, почему бы просто не вывести этот элемент?

```
arr = { day_of_week: available}
```

Не совсем для меня понятен принцип действия условия, если вы просто проверятете текущий день то зачем использовать для этого массив, по-крайней мере в этом месте (если нужно выводить в контроллере результатом массив то можно результат выполнения уже преобразовать).

**Comment by mira-matsakova** [comment]
Согласна! в этом условии нет смысла

**Comment by mira-matsakova** [comment]
Исправлено https://github.com/alex-rns/med_helper/blob/refactoring/app/helpers/events_helper.rb
