### ISSUE TITLE
redundant

### ISSUE THREAD

**Issue by xandrck** [alex-rns/med_helper#138]
https://github.com/alex-rns/med_helper/blob/58c076f69090b6c0c017d8fe2c1f46f0088f0cf6/app/helpers/experts_helper.rb#L9
```
arr.each_with_index.map { |x,i| [x.name, i+1] }
```
https://github.com/alex-rns/med_helper/blob/58c076f69090b6c0c017d8fe2c1f46f0088f0cf6/app/helpers/experts_helper.rb#L14

**Comment by alex-rns** [comment]
Fixed! https://github.com/alex-rns/med_helper/commit/160994244799d595646086773eceaf70db14bcdf
