### ISSUE TITLE
refactore

### ISSUE THREAD

**Issue by xandrck** [alex-rns/med_helper#140]
https://github.com/alex-rns/med_helper/blob/58c076f69090b6c0c017d8fe2c1f46f0088f0cf6/app/models/user.rb#L15

https://github.com/alex-rns/med_helper/blob/58c076f69090b6c0c017d8fe2c1f46f0088f0cf6/app/models/user.rb#L23
думаю можно в некоторых случаях вытаскивать и ДР, по-этому стоит обработать этот момент

https://github.com/alex-rns/med_helper/blob/58c076f69090b6c0c017d8fe2c1f46f0088f0cf6/app/models/user.rb#L24
не секьюрный пароль + хардкод, нужно генерить рандомный и отсылать на почту

**Comment by mira-matsakova** [comment]
Пароль нужно выкинуть, так как он не используется в проекте. Что касается даты, то надо почитать ещё раз доку наверника есть способ вытащить дату.

**Comment by mira-matsakova** [comment]
Добавила секьюрный пасворд https://github.com/alex-rns/med_helper/commit/d6747ba9e57e09b8aa1717a9c8d1ef1dfd8c8cd9
