### ISSUE TITLE
helper

### ISSUE THREAD

**Issue by xandrck** [alex-rns/med_helper#141]
https://github.com/alex-rns/med_helper/blob/58c076f69090b6c0c017d8fe2c1f46f0088f0cf6/app/views/children/index.html.erb#L17
```
.strftime("%d of %B, %Y")
```
используется 77 раз в проекте, думаю это намёк на то что это можно вынести в хелпер или транслейт
https://guides.rubyonrails.org/i18n.html#adding-date-time-formats

**Comment by alex-rns** [comment]
Пофикшено! https://github.com/alex-rns/med_helper/commit/95212db6aee0069e06bb577f421abe7d3f4800f1
