### ISSUE TITLE
helper

### ISSUE THREAD

**Issue by xandrck** [alex-rns/med_helper#144]
https://github.com/alex-rns/med_helper/blob/58c076f69090b6c0c017d8fe2c1f46f0088f0cf6/app/views/experts/_time_slots.html.erb#L3
Тут мастехев в хелпер

https://github.com/alex-rns/med_helper/blob/58c076f69090b6c0c017d8fe2c1f46f0088f0cf6/app/views/experts/_time_slots.html.erb#L4
одно и тоже использование что и выше

```
<%= link_to "00:00", new_expert_event_path(expert, q: time_helper(0)), class: "btn btn-outline-primary rounded", date_time: time_helper(0) if check_params(expert, time_helper(0)) %>
```
это как минимум но тут снова не ясный для меня подходи с хардкордными значениями

тут нужно использовать просто вместо всех ифов
```
<%= link_to "00:00", new_expert_event_path(expert, q: time_helper(val)), class: "btn btn-outline-primary rounded", date_time: time_helper(val) if check_params(expert, time_helper(val)) %>
```

а вот тут
https://github.com/alex-rns/med_helper/blob/58c076f69090b6c0c017d8fe2c1f46f0088f0cf6/app/helpers/experts_helper.rb#L18
обрабатывать массив из 0 - 23 (я правда не понял почем именно 23) и выводить первый элемент со значением true тогда вы динамически сможете работать с этими значениями и не нужно будет кучу не нужных сложностей с этими условиями

**Comment by mira-matsakova** [comment]
Мы выкинули тайм слоты на странице с поиском эксперта, так как особого смысла в них нет, потому что они выполняли только одну функцию: доступное время для записи на приём на текущий день. Вместо этого добавили тайм слоты, которые можно посмотреть на любой день выбрав в календаре любую дату на странице записи на приём. Тайм слоты были скрыты на вьюхе, но код не был удалён, сейчас я удалила ненужный код.
