### ISSUE TITLE
redundant

### ISSUE THREAD

**Issue by xandrck** [alex-rns/med_helper#146]
https://github.com/alex-rns/med_helper/blob/58c076f69090b6c0c017d8fe2c1f46f0088f0cf6/app/views/layouts/_navbar.html.erb#L35
Какую роль тут выполняет else?

**Comment by alex-rns** [comment]
Упс..Исправлено https://github.com/alex-rns/med_helper/commit/87d37076f0116e170a8e4a0bd455d28e526170fe
