### ISSUE TITLE
to many conditions, posible improve

### ISSUE THREAD

**Issue by xandrck** [alex-rns/med_helper#148]
https://github.com/alex-rns/med_helper/blob/58c076f69090b6c0c017d8fe2c1f46f0088f0cf6/app/views/users/_doctor.html.erb#L8
с кол-вом условий перебор, если вы не хотите отображать поля тогда можно обработать информацию и возвращать только поля с данными

```
###Controller
@user_fields_hash = {
  fio: @user.expert.full_name,
  desc: @user.expert.description
}
```

https://apidock.com/rails/ActionView/Helpers/TagHelper/content_tag
```
###Helper
def user_fields(key, val)
 content_tag(:p) do
   content_tag(:strong) do
      "#{user_keys[key]}:"
   end
  concat(val)
 end
end

###
user_keys: {
  fio: ФИО,
  desc: Краткое описание
}
```

```
###View

@user_fields_hash.each do |key, val|
  <%= user_fields(key, val)  %>
end
```

будет круто если сможете реализовать

**Comment by alex-rns** [comment]
А где и как лучше сетить хэш?
 user_keys: {
  fio: ФИО,
  desc: Краткое описание
}

**Comment by mira-matsakova** [comment]
Исправлено https://github.com/alex-rns/med_helper/commit/69faffba2709aa7c6b43279c8ee26b56ee33b45d но все таки остается вопрос как лучше сетить user_keys(вопрос выше)
