### ISSUE TITLE
controller logic

### ISSUE THREAD

**Issue by xandrck** [alex-rns/med_helper#149]
https://github.com/alex-rns/med_helper/blob/58c076f69090b6c0c017d8fe2c1f46f0088f0cf6/app/views/vaccines/show.html.erb#L1
переменные должны объявляться в контроллере, на крайний случай используйте хелпер

**Comment by alex-rns** [comment]
Исправлено https://github.com/alex-rns/med_helper/commit/02bd75b037a7cec1a3905e0773fd8f7f5233406c
